In [1]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.8.2)
Requirement already satisfied: soupsieve>=1.2 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from beautifulsoup4) (1.9.5)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install lxml

Requirement already satisfied: lxml in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.4.2)
Note: you may need to restart the kernel to use updated packages.

## Importing libaries

In [4]:
#Importing libraries

from bs4 import BeautifulSoup
import requests
import pandas as pd

## Creating a dataframe of Neighbourhood data

In [5]:
#Creating a dataframe

dfs = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')
for df in dfs:
    print(df)

    Postcode           Borough          Neighbourhood
0        M1A      Not assigned           Not assigned
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
..       ...               ...                    ...
282      M8Z         Etobicoke              Mimico NW
283      M8Z         Etobicoke     The Queensway West
284      M8Z         Etobicoke  Royal York South West
285      M8Z         Etobicoke         South of Bloor
286      M9Z      Not assigned           Not assigned

[287 rows x 3 columns]
                                                  0   \
0                                                NaN
1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
2                                                 NL
3                                                  A

                                                  1   \
0                              Canadian postal codes
1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
2                                                 NS
3                                                  B

                                                  2    3    4    5    6    7   \
0                                                NaN  NaN  NaN  NaN  NaN  NaN
1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
2                                                 PE   NB   QC   QC   QC   ON
3                                                  C    E    G    H    J    K

    8    9    10   11   12   13   14   15     16   17
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
3    L    M    N    P    R    S    T    V      X    Y
   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y

## Cleaning the Dataframe

In [6]:
#Creating a dataframe after eliminating unnecessary tables
Canada=dfs[0]
Canada

    Postcode           Borough          Neighbourhood
0        M1A      Not assigned           Not assigned
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
..       ...               ...                    ...
282      M8Z         Etobicoke              Mimico NW
283      M8Z         Etobicoke     The Queensway West
284      M8Z         Etobicoke  Royal York South West
285      M8Z         Etobicoke         South of Bloor
286      M9Z      Not assigned           Not assigned

[287 rows x 3 columns]

In [7]:
#Removing rows which have do not have an assigned Borough

import numpy as np

Canada['Borough']=Canada['Borough'].replace('Not assigned',np.nan)
Canada=Canada.dropna(axis=0,subset=['Borough'])
Canada

    Postcode           Borough             Neighbourhood
2        M3A        North York                 Parkwoods
3        M4A        North York          Victoria Village
4        M5A  Downtown Toronto              Harbourfront
5        M6A        North York          Lawrence Heights
6        M6A        North York            Lawrence Manor
..       ...               ...                       ...
281      M8Z         Etobicoke  Kingsway Park South West
282      M8Z         Etobicoke                 Mimico NW
283      M8Z         Etobicoke        The Queensway West
284      M8Z         Etobicoke     Royal York South West
285      M8Z         Etobicoke            South of Bloor

[210 rows x 3 columns]

In [8]:
#Aggregating neigbourhoods who have same postcode

Canada_1=Canada.groupby('Postcode').agg(lambda x:','.join(set(x)))
Canada_1

              Borough                                      Neighbourhood
Postcode
M1B       Scarborough                                      Malvern,Rouge
M1C       Scarborough               Highland Creek,Rouge Hill,Port Union
M1E       Scarborough                    Morningside,Guildwood,West Hill
M1G       Scarborough                                             Woburn
M1H       Scarborough                                          Cedarbrae
...               ...                                                ...
M9N              York                                             Weston
M9P         Etobicoke                                          Westmount
M9R         Etobicoke  Richview Gardens,Kingsview Village,St. Phillip...
M9V         Etobicoke  Mount Olive,South Steeles,Thistletown,Silverst...
M9W         Etobicoke                                          Northwest

[103 rows x 2 columns]

In [9]:
#Filling up not assigned Neighbourhoods with boroughs

Canada_1.loc[Canada_1['Neighbourhood']=="Not assigned",'Neighbourhood']=Canada_1.loc[Canada_1['Neighbourhood']=="Not assigned",'Borough']
Canada_1

              Borough                                      Neighbourhood
Postcode
M1B       Scarborough                                      Malvern,Rouge
M1C       Scarborough               Highland Creek,Rouge Hill,Port Union
M1E       Scarborough                    Morningside,Guildwood,West Hill
M1G       Scarborough                                             Woburn
M1H       Scarborough                                          Cedarbrae
...               ...                                                ...
M9N              York                                             Weston
M9P         Etobicoke                                          Westmount
M9R         Etobicoke  Richview Gardens,Kingsview Village,St. Phillip...
M9V         Etobicoke  Mount Olive,South Steeles,Thistletown,Silverst...
M9W         Etobicoke                                          Northwest

[103 rows x 2 columns]

## Finding the number of rows in the final dataframe

In [16]:
#finding number of rows in the dataframe
print("The number of rows in the cleansed data set are:",Canada_1.shape[0])

The number of rows in the cleansed data set are: 103